name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [10, 11]
        include:
          - php: 8.4
            laravel: 11
          - php: 8.2
            laravel: 9
          - php: 8.1
            laravel: 9
          - php: '8.0'
            laravel: 9
        exclude:
          - php: 8.1
            laravel: 11

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
           composer update --prefer-dist --no-interaction --no-progress --with="illuminate/contracts=^${{ matrix.laravel }}"

      - name: Execute tests
        run: vendor/bin/phpunit

  tests-using-meilisearch:
    runs-on: ubuntu-22.04

    services:
      meilisearch:
        image: getmeili/meilisearch:latest
        ports:
          - 7700:7700
        env:
          MEILI_MASTER_KEY: masterKey
          MEILI_NO_ANALYTICS: true

    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', 8.1, 8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }} using Meilisearch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
           composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --no-configuration --no-coverage --color --bootstrap vendor/autoload.php --group meilisearch tests/Integration
        env:
          MEILISEARCH_HOST: "http://localhost:7700"
          MEILISEARCH_KEY: 'masterKey'
          DB_CONNECTION: 'testing'

  tests-using-typesense:
    runs-on: ubuntu-22.04

    services:
        typesense:
            image: typesense/typesense:0.25
            ports:
            - 8108:8108/tcp
            volumes:
            - /tmp/typesense-server-data:/data
            env:
                TYPESENSE_DATA_DIR: /data
                TYPESENSE_API_KEY: xyz
                TYPESENSE_ENABLE_CORS: true

    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', 8.1, 8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }} using Typesense

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: dom, curl, libxml, mbstring, zip
            ini-values: error_reporting=E_ALL
            tools: composer:v2
            coverage: none

        - name: Install dependencies
          run: |
            composer update --prefer-dist --no-interaction --no-progress

        - name: Execute tests
          run: vendor/bin/phpunit --no-configuration --no-coverage --color --bootstrap vendor/autoload.php --group typesense tests/Integration
          env:
            TYPESENSE_HOST: "localhost"
            TYPESENSE_PORT: 8108
            TYPESENSE_API_KEY: 'xyz'
            DB_CONNECTION: 'testing'
